version: "3.9"

services:
  mariadb:
    container_name: MariaDB
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: neuro
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: neuronalnet
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - NeuronalNetServer/Migrations:/docker-entrypoint-initdb.d

  neuronalnetserver:
    container_name: NeuronalNetServer
    image: neuronalnetserver
    restart: always
    build:
      context: .
      dockerfile: NeuronalNetServer/Dockerfile
    ports:
      - 7613:7613
    depends_on:
      - mariadb
      

  neuronalnetclient:
    container_name: NeuronalNetClient
    image: neuronalnetclient
    restart: always
    build:
      context: .
      dockerfile: NeuronalNetClient/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - neuronalnetserver
